In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/ai4i2020.csv")

df.head()

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF
0,1,M14860,M,298.1,308.6,1551,42.8,0,0,0,0,0,0,0
1,2,L47181,L,298.2,308.7,1408,46.3,3,0,0,0,0,0,0
2,3,L47182,L,298.1,308.5,1498,49.4,5,0,0,0,0,0,0
3,4,L47183,L,298.2,308.6,1433,39.5,7,0,0,0,0,0,0
4,5,L47184,L,298.2,308.7,1408,40.0,9,0,0,0,0,0,0

In [2]:
df.columns.tolist()

['UDI',
 'Product ID',
 'Type',
 'Air temperature [K]',
 'Process temperature [K]',
 'Rotational speed [rpm]',
 'Torque [Nm]',
 'Tool wear [min]',
 'Machine failure',
 'TWF',
 'HDF',
 'PWF',
 'OSF',
 'RNF']

In [4]:
df = df.drop(columns=["UDI", "Product ID"])

In [5]:
df.head()

,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF
0,M,298.1,308.6,1551,42.8,0,0,0,0,0,0,0
1,L,298.2,308.7,1408,46.3,3,0,0,0,0,0,0
2,L,298.1,308.5,1498,49.4,5,0,0,0,0,0,0
3,L,298.2,308.6,1433,39.5,7,0,0,0,0,0,0
4,L,298.2,308.7,1408,40.0,9,0,0,0,0,0,0

In [6]:
df = df.drop(columns=["TWF", "HDF", "PWF", "OSF", "RNF"])

In [7]:
X = df.drop(columns=["Machine failure"])
y = df["Machine failure"]

In [8]:
print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (10000, 6)
y shape: (10000,)

In [9]:
X = pd.get_dummies(
    X,
    columns=["Type"],
    drop_first=True
)

In [10]:
X.head()

,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Type_L,Type_M
0,298.1,308.6,1551,42.8,0,False,True
1,298.2,308.7,1408,46.3,3,True,False
2,298.1,308.5,1498,49.4,5,True,False
3,298.2,308.6,1433,39.5,7,True,False
4,298.2,308.7,1408,40.0,9,True,False

In [11]:
print(X.isnull().sum())

Air temperature [K]        0
Process temperature [K]    0
Rotational speed [rpm]     0
Torque [Nm]                0
Tool wear [min]            0
Type_L                     0
Type_M                     0
dtype: int64

In [12]:
print(y.isnull().sum())

0

In [15]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [16]:
print("Training set:")
print(y_train.value_counts(normalize=True))

print("\nTesting set:")
print(y_test.value_counts(normalize=True))

Training set:
Machine failure
0    0.966125
1    0.033875
Name: proportion, dtype: float64

Testing set:
Machine failure
0    0.966
1    0.034
Name: proportion, dtype: float64

In [17]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [18]:
scaler.fit_transform(X_train)

array([[ 0.99891359,  0.60428162, -0.46060741, ..., -0.84399726,
        -1.23436595,  1.53620728],
       [-1.50519408, -1.15325984, -0.77557391, ...,  0.38226308,
        -1.23436595,  1.53620728],
       [ 0.49809206,  1.07746586, -1.00765448, ...,  0.46086951,
        -1.23436595,  1.53620728],
       ...,
       [ 0.14751698,  1.00986812, -0.41640159, ..., -1.23702942,
        -1.23436595, -0.65095382],
       [ 0.84866713,  0.80707487, -0.12353801, ...,  0.08355864,
         0.81013252, -0.65095382],
       [-0.65379747, -0.20689136, -0.42745305, ..., -1.63006158,
         0.81013252, -0.65095382]], shape=(8000, 7))

In [19]:
scaler.transform(X_test)

array([[ 0.24768129, -0.13929361, -1.07396322, ...,  0.71241009,
         0.81013252, -0.65095382],
       [ 1.85031019,  1.61824785, -0.14564092, ...,  0.42942694,
         0.81013252, -0.65095382],
       [ 1.24932436,  0.94227037,  0.10854256, ...,  1.59280213,
         0.81013252, -0.65095382],
       ...,
       [-0.95429039, -1.42365083, -0.51586469, ...,  0.20932893,
        -1.23436595,  1.53620728],
       [ 1.1992422 ,  1.28025911, -0.64848216, ...,  1.35698283,
        -1.23436595,  1.53620728],
       [-1.0544547 , -0.6800756 ,  2.37961675, ..., -1.11125913,
        -1.23436595,  1.53620728]], shape=(2000, 7))

In [20]:
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (8000, 7)
X_test: (2000, 7)
y_train: (8000,)
y_test: (2000,)